### ISSUE TITLE
Missing line break after error

### ISSUE THREAD

**Issue by AliAlmohsen** [krasimir/hopa#3]
If a file I select throws an error, then you break (Ctrl+C), your terminal continues on the same line as the end of the error. There should be a line break after the error.

![Screenshot from 2020-01-16 10-54-49](https://user-images.githubusercontent.com/51526307/72504395-cca21400-384e-11ea-91de-0c1c6de2ca37.png)

**Comment by krasimir** [comment]
Just released 1.3.1. Should be fixed now.

**Comment by krasimir** [comment]
Is this fixed for you @AliRain

**Comment by AliAlmohsen** [comment]
Yup, looks good now. Thanks!
