### ISSUE TITLE
Error quickly flashes before each run if no tsconfig found

### ISSUE THREAD

**Issue by AliAlmohsen** [krasimir/hopa#8]
I'm using hopa for js, not ts, so I don't have a tsconfig file. On each save, I see the following error for like half a second before it starts running my file:
![Screenshot from 2020-02-25 12-47-35](https://user-images.githubusercontent.com/51526307/75235480-5db0c700-57cd-11ea-8d0f-99d817f9feba.png)

**Comment by qchenevier** [comment]
Same issue here, also for js files.

The error is briefly displayed before the run.

Then the error is flashed 1 second after and stays below my script output.

**Comment by krasimir** [comment]
Hey, can you paste the content of your file here. Also node version and OS will be helpful.

**Comment by AliAlmohsen** [comment]
node v12.16.3
Linux Mint 19.3 Tricia

The error disappears if you create a tsconfig, which isn't needed if you're just using hopa for JS.

**Comment by krasimir** [comment]
Interesting, `tsconfig.js` in the folder where you run hopa?

**Comment by AliAlmohsen** [comment]
If I have a tsconfig in the folder, the error doesn't appear. If I don't have one, I see the error.

**Comment by krasimir** [comment]
Awesome. That's enough. I'll debug.

**Comment by krasimir** [comment]
@AliRain @qchenevier it should be fixed now. Can you please try the latest version `npm i hopa@latest`.

[fix](https://github.com/krasimir/hopa/commit/e6094787d8ee134bb511180a7f6ae8e096123da0)

**Comment by qchenevier** [comment]
It works for me. You rock !

**Comment by krasimir** [comment]
@AliRain I hope it works for you too. If not please comment below. Closing for now.
